kbuild: Use --btf_encode_force for BTF with gcc lto
pahole -J doesn't like some of the dwarf generated for percpu variables
by gcc LTO. It errors out with

error: found variable '__percpu_rwsem_rc_cpu_hotplug_lock' in CU '' that has void type
etc.

Pass --btf_encode_force to ignore those errors for now. Root cause
still unknown. I guess we can live without BTF for some
percpu variables for now.

Signed-off-by: Andi Kleen <andi@firstfloor.org>